language: python
env:
  - DJANGO_VERSION='>=1.8'
python:
  - 2.7
  - "pypy"
  - "3.4"
  - "3.5"
install:
  - pip install -q Django$DJANGO_VERSION
  - pip install -r requirements.txt
script: python run_tests.py
