language: python
env:
  - DJANGO_VERSION='<1.7'
  - DJANGO_VERSION='>=1.7'
python:
  - 2.7
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install -q Django$DJANGO_VERSION
  - pip install -r requirements.txt
script: python run_tests.py
